name: Optimize Resource Pack
on:
  push:
    tags:
      - "*"
    paths:
      - 'pack/**'
      - '.github/workflows/packsquash.yml'
jobs:
  packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # 変更しないでください
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2
        with:
          path: pack
          # allow_optifine_mod: true
      - name: Download Optimized Pack
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
      - name: Rename Pack Name
        run: mv pack.zip MCChampions-ResourcePack.zip
      - name: Get The Version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          files: |
            MCChampions-ResourcePack.zip
